# Generated by Django 5.2.9 on 2025-12-24 16:46

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpertiseIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('introduction', wagtail.fields.RichTextField(blank=True, verbose_name='Introduction')),
                ('hero_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name="Image d'en-tête")),
            ],
            options={
                'verbose_name': 'Page nos expertises',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ExpertisePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('summary', models.TextField(blank=True, max_length=500, verbose_name='petit text')),
                ('description', wagtail.fields.RichTextField(blank=True, verbose_name='Description détaillée')),
                ('passe_to_action', wagtail.fields.RichTextField(blank=True, verbose_name="Passer à l'action")),
                ('faq', wagtail.fields.StreamField([('items', 3)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'label': 'Question'}), 1: ('wagtail.blocks.RichTextBlock', (), {'label': 'Réponse'}), 2: ('wagtail.blocks.StructBlock', [[('question', 0), ('answer', 1)]], {}), 3: ('wagtail.blocks.ListBlock', (2,), {})})),
                ('featured_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Image principale')),
            ],
            options={
                'verbose_name': 'Page Expertise',
            },
            bases=('wagtailcore.page',),
        ),
    ]
