# Generated by Django 5.2.9 on 2025-12-25 10:34

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expertise', '0002_expertiseindexpage_benifits_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expertiseindexpage',
            name='benifits',
        ),
        migrations.RemoveField(
            model_name='expertiseindexpage',
            name='content',
        ),
        migrations.RemoveField(
            model_name='expertiseindexpage',
            name='services',
        ),
        migrations.AddField(
            model_name='expertisepage',
            name='benifits',
            field=wagtail.fields.StreamField([('items', 2)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'label': 'Description'}), 1: ('wagtail.blocks.StructBlock', [[('description', 0)]], {}), 2: ('wagtail.blocks.ListBlock', (1,), {})}),
        ),
        migrations.AddField(
            model_name='expertisepage',
            name='content',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='Contenu'),
        ),
        migrations.AddField(
            model_name='expertisepage',
            name='services',
            field=wagtail.fields.StreamField([('items', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Titre'}), 1: ('wagtail.blocks.RichTextBlock', (), {'label': 'Description'}), 2: ('wagtail.blocks.StructBlock', [[('title', 0), ('description', 1)]], {}), 3: ('wagtail.blocks.ListBlock', (2,), {})}),
        ),
    ]
