# Generated by Django 5.2.9 on 2026-05-30 14:36

import django.db.models.deletion
import modelcluster.fields
import wagtail.contrib.forms.models
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecruitmentIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('to_address', models.CharField(blank=True, help_text='Optional - form submissions will be emailed to these addresses. Separate multiple addresses by comma.', max_length=255, validators=[wagtail.contrib.forms.models.validate_to_address], verbose_name='to address')),
                ('from_address', models.EmailField(blank=True, max_length=255, verbose_name='from address')),
                ('subject', models.CharField(blank=True, max_length=255, verbose_name='subject')),
                ('introduction', wagtail.fields.RichTextField(blank=True)),
                ('testimonials', wagtail.fields.StreamField([('testimonial', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Nom'}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Poste'}), 2: ('wagtail.blocks.TextBlock', (), {'label': 'Citation'}), 3: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Photo', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('name', 0), ('role', 1), ('quote', 2), ('photo', 3)]], {})}, verbose_name='Témoignages collaborateurs')),
                ('hide_on_pc', models.BooleanField(default=True, verbose_name='Masquer sur PC')),
                ('hero_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name="Image d'en-tête")),
            ],
            options={
                'verbose_name': 'Page Recrutement',
            },
            bases=(wagtail.contrib.forms.models.FormMixin, 'wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='JobApplicationFormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('clean_name', models.CharField(blank=True, default='', help_text='Safe name of the form field, the label converted to ascii_snake_case', max_length=255, verbose_name='name')),
                ('label', models.CharField(help_text='The label of the form field', max_length=255, verbose_name='label')),
                ('required', models.BooleanField(default=True, verbose_name='required')),
                ('choices', models.TextField(blank=True, help_text='Comma or new line separated list of choices. Only applicable in checkboxes, radio and dropdown.', verbose_name='choices')),
                ('default_value', models.TextField(blank=True, help_text='Default value. Comma or new line separated values supported for checkboxes.', verbose_name='default value')),
                ('help_text', models.CharField(blank=True, max_length=255, verbose_name='help text')),
                ('field_type', models.CharField(choices=[('singleline', 'Single line text'), ('multiline', 'Multi-line text'), ('email', 'Email'), ('number', 'Number'), ('url', 'URL'), ('checkbox', 'Checkbox'), ('checkboxes', 'Checkboxes'), ('dropdown', 'Drop down'), ('multiselect', 'Multiple select'), ('radio', 'Radio buttons'), ('date', 'Date'), ('datetime', 'Date/time'), ('hidden', 'Hidden field'), ('document', 'Upload Document')], max_length=16, verbose_name='field type')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_fields', to='recruitment.recruitmentindexpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContractType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Type de contrat')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_types', to='recruitment.recruitmentindexpage')),
            ],
        ),
        migrations.CreateModel(
            name='RecruitmentPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('job_title', models.CharField(max_length=255, verbose_name='Poste')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='Localisation')),
                ('body', wagtail.fields.RichTextField(blank=True, verbose_name='Description')),
                ('salary', models.CharField(blank=True, max_length=255, verbose_name='Salaire')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Date')),
                ('contract_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recruitment_pages', to='recruitment.contracttype', verbose_name='Type de contrat')),
            ],
            options={
                'verbose_name': 'Page Recrutement',
            },
            bases=('wagtailcore.page',),
        ),
    ]
