# Generated by Django 5.2.9 on 2025-12-25 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplicationsubmission',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='job_applications/'),
        ),
    ]
