# Generated by Django 5.2.9 on 2025-12-25 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0003_spontaneousapplication_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SpontaneousApplication',
        ),
    ]
