# Generated by Django 5.2.9 on 2025-12-24 16:46

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemLegalPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('summary', models.CharField(blank=True, max_length=255, verbose_name='Résumé')),
                ('description', wagtail.fields.RichTextField(blank=True, verbose_name='Description détaillée')),
                ('featured_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Image principale')),
            ],
            options={
                'verbose_name': 'notions des  mentions legales',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='LegalPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('hero_title', models.CharField(default='Mentions Légales & RGPD', max_length=255, verbose_name='Titre principal')),
                ('introduction', wagtail.fields.RichTextField(blank=True, verbose_name='Introduction')),
                ('featured_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Image principale')),
            ],
            options={
                'verbose_name': 'Page Mentions légales & RGPD',
            },
            bases=('wagtailcore.page',),
        ),
    ]
