# Generated by Django 5.2.9 on 2026-05-31 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FqaClient',
            new_name='FqaServicesProvided',
        ),
        migrations.AlterModelOptions(
            name='fqaservicesprovided',
            options={'verbose_name': 'The services provided by Maioreb are:', 'verbose_name_plural': 'The services provided by Maioreb are:'},
        ),
    ]
