# Generated by Django 5.2.9 on 2025-12-29 16:17

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contactpage_recipients_emails'),
    ]

    operations = [
        migrations.CreateModel(
            name='FqaClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faq', wagtail.fields.StreamField([('items', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'question', 'required': True}), 1: ('wagtail.blocks.RichTextBlock', (), {'label': 'answer', 'required': True}), 2: ('wagtail.blocks.StructBlock', [[('question', 0), ('answer', 1)]], {}), 3: ('wagtail.blocks.ListBlock', (2,), {})})),
            ],
        ),
    ]
