# Generated by Django 5.2.9 on 2026-05-31 10:51

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_rename_fqaclient_fqaservicesprovided_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fqaservicesprovided',
            name='faq',
            field=wagtail.fields.StreamField([('items', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'service', 'required': True}), 1: ('wagtail.blocks.RichTextBlock', (), {'label': 'detail', 'required': True}), 2: ('wagtail.blocks.StructBlock', [[('service', 0), ('detail', 1)]], {}), 3: ('wagtail.blocks.ListBlock', (2,), {})}),
        ),
    ]
