# Generated by Django 5.2.9 on 2026-06-01 08:32

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_alter_fqaservicesprovided_faq'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactpage',
            name='address',
        ),
        migrations.AddField(
            model_name='contactpage',
            name='location',
            field=wagtail.fields.StreamField([('addresses', 1)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Address'}), 1: ('wagtail.blocks.ListBlock', (0,), {})}, verbose_name='Addresses'),
        ),
    ]
