# Generated by Django 5.2.9 on 2025-12-29 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_fqaclient'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fqaclient',
            options={'verbose_name': 'questions et réponses client', 'verbose_name_plural': 'questions et réponses clients'},
        ),
    ]
