# Generated by Django 5.2.9 on 2026-06-01 08:50

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_remove_contactpage_address_contactpage_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactpage',
            name='location',
            field=wagtail.fields.StreamField([('locations', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': True}), 1: ('wagtail.blocks.TextBlock', (), {'required': False}), 2: ('wagtail.blocks.StructBlock', [[('address', 0), ('map_embed_code', 1)]], {}), 3: ('wagtail.blocks.ListBlock', (2,), {})}, verbose_name='Locations'),
        ),
    ]
