# Generated by Django 5.2.9 on 2025-12-29 20:10

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_alter_fqaclient_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fqaclient',
            name='faq',
        ),
        migrations.AddField(
            model_name='fqaclient',
            name='faq_client',
            field=wagtail.fields.StreamField([('question', 0), ('answer', 1)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'question', 'required': True}), 1: ('wagtail.blocks.RichTextBlock', (), {'label': 'answer', 'required': True})}),
        ),
    ]
