# Generated by Django 5.2.9 on 2025-12-29 20:15

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_remove_fqaclient_faq_fqaclient_faq_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fqaclient',
            name='faq_client',
        ),
        migrations.AddField(
            model_name='fqaclient',
            name='faq',
            field=wagtail.fields.StreamField([('items', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'question', 'required': True}), 1: ('wagtail.blocks.RichTextBlock', (), {'label': 'answer', 'required': True}), 2: ('wagtail.blocks.StructBlock', [[('question', 0), ('answer', 1)]], {}), 3: ('wagtail.blocks.ListBlock', (2,), {})}),
        ),
    ]
