# Generated by Django 5.2.9 on 2026-06-01 09:32

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0006_alter_contactpage_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactpage',
            name='location',
            field=wagtail.fields.StreamField([('locations', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': True}), 1: ('wagtail.blocks.TextBlock', (), {'required': False}), 2: ('wagtail.blocks.FloatBlock', (), {'required': False}), 3: ('wagtail.blocks.StructBlock', [[('label', 0), ('address', 0), ('google_maps_link', 1), ('latitude', 2), ('longitude', 2)]], {}), 4: ('wagtail.blocks.ListBlock', (3,), {})}, verbose_name='Locations'),
        ),
    ]
