# Generated by Django 5.2.9 on 2026-06-01 16:03

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0007_alter_contactpage_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactpage',
            name='recipients_emails',
            field=wagtail.fields.StreamField([('email', 0)], blank=True, block_lookup={0: ('wagtail.blocks.EmailBlock', (), {})}, verbose_name='emails qui recevront les formulaires de contact '),
        ),
    ]
