# Generated by Django 5.2.9 on 2025-12-24 16:46

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='CookieConsentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('message', models.TextField(default='We use cookies to improve your experience.')),
                ('privacy_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Cookie Consent',
            },
        ),
        migrations.CreateModel(
            name='CulturePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('introduction', wagtail.fields.RichTextField(blank=True)),
                ('culture_content', wagtail.fields.StreamField([('element', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Titre'}), 1: ('wagtail.blocks.RichTextBlock', (), {'label': 'Texte'}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Image', 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('title', 0), ('text', 1), ('image', 2)]], {})}, verbose_name='Ambiance / Culture interne')),
                ('hero_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name="Image d'en-tête")),
            ],
            options={
                'verbose_name': 'Page culture et ambiance',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('hero_title', models.CharField(default='Nous sommes ATR-IS.', max_length=255, verbose_name="Titre principal(ce titre déroule sur le ruban dans page d'accueil)")),
                ('hero_subtitle', models.CharField(blank=True, max_length=500, verbose_name='Sous-titre')),
                ('slides', wagtail.fields.StreamField([('slide', 5)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Image de fond du slide', 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Titre principal', 'max_length': 255, 'required': True}), 2: ('wagtail.blocks.TextBlock', (), {'help_text': 'Sous-titre du slide', 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'default': 'Entrer dans l’univers ATR-IS', 'max_length': 50, 'required': False}), 4: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'Lien du bouton CTA', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('background_image', 0), ('hero_title', 1), ('hero_subtitle', 2), ('hero_cta_text', 3), ('cta_linked_page', 4)]], {})}, verbose_name='Slides du hero')),
                ('video', models.URLField(blank=True, verbose_name='Vidéo (YouTube/Vimeo)')),
                ('hero_cta_text', models.CharField(default='Entrer dans l’univers ATR-IS', max_length=50, verbose_name='Texte du bouton CTA')),
                ('introduction', wagtail.fields.RichTextField(blank=True, verbose_name='Introduction')),
                ('presedant_name', models.CharField(blank=True, max_length=255, verbose_name='Nom presedant')),
                ('presedant_message', wagtail.fields.RichTextField(blank=True, verbose_name='Message presedant')),
                ('posts_linkedin', wagtail.fields.StreamField([('items', 5)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.blocks.URLBlock', (), {}), 3: ('wagtail.blocks.DateBlock', (), {}), 4: ('wagtail.blocks.StructBlock', [[('image', 0), ('introduction', 1), ('link', 2), ('date', 3)]], {}), 5: ('wagtail.blocks.ListBlock', (4,), {})})),
                ('cta_linked_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Lien du bouton CTA')),
                ('favicon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='favicon')),
                ('logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='logo')),
                ('presedant_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Image président')),
            ],
            options={
                'verbose_name': "Page d'Accueil",
            },
            bases=('wagtailcore.page',),
        ),
    ]
