# Generated by Django 5.2.9 on 2026-05-31 10:46

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='hero_cta_text',
            field=models.CharField(default='what we do', max_length=50, verbose_name='Texte du bouton CTA'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='slides',
            field=wagtail.fields.StreamField([('slide', 1)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Image de fond du slide', 'required': True}), 1: ('wagtail.blocks.StructBlock', [[('background_image', 0)]], {})}, verbose_name='Slides du hero'),
        ),
    ]
