# Generated by Django 5.2.9 on 2026-06-01 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_homepage_hero_cta_text_alter_homepage_slides'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='posts_linkedin',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='presedant_image',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='presedant_message',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='presedant_name',
        ),
        migrations.AddField(
            model_name='homepage',
            name='home_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name="Image de la première section de la page d'accueil"),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_subtitle',
            field=models.CharField(blank=True, max_length=500, verbose_name='petite introduction dans la section hero'),
        ),
    ]
