# Generated by Django 5.2.9 on 2025-12-30 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_homepage_sectors'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='hero_title_2',
            field=models.CharField(default='Nous sommes ATR-IS.', max_length=255, verbose_name='Titre secondaire(ce titre afficher dans hero section apres le titre principal)'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_subtitle',
            field=models.CharField(blank=True, max_length=500, verbose_name='petite introduction(afficher dans hero section avant le CTA)'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_title',
            field=models.CharField(default='Nous sommes ATR-IS.', max_length=255, verbose_name="Titre principal(ce titre afficher dans hero section et déroule sur le ruban dans page d'accueil)"),
        ),
    ]
