# Generated by Django 5.2.9 on 2025-12-24 16:46

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntrepriseIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('not_clicable', models.BooleanField(default=True, verbose_name='Non cliquable')),
            ],
            options={
                'verbose_name': 'Entreprise',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('introduction', wagtail.fields.RichTextField(blank=True, verbose_name='Introduction')),
                ('mission_title', models.CharField(default='Nos Missions', max_length=255, verbose_name='Titre de la mission')),
                ('mission_content', wagtail.fields.RichTextField(blank=True, verbose_name='Contenu de la mission')),
                ('vision_title', models.CharField(default='Nos Vision', max_length=255, verbose_name='Titre de la vision')),
                ('vision_content', wagtail.fields.RichTextField(blank=True, verbose_name='Contenu de la vision')),
                ('values_title', models.CharField(default='Nos Valeurs', max_length=255, verbose_name='Titre des valeurs')),
                ('values', wagtail.fields.StreamField([('values_items', 3)], blank=True, block_lookup={0: ('wagtail.blocks.TextBlock', (), {'label': 'titre', 'required': True}), 1: ('wagtail.blocks.RichTextBlock', (), {'label': 'Description', 'required': True}), 2: ('wagtail.blocks.StructBlock', [[('title', 0), ('description', 1)]], {}), 3: ('wagtail.blocks.ListBlock', (2,), {})})),
                ('timeline', wagtail.fields.StreamField([('items', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'année', 'required': True}), 1: ('wagtail.blocks.TextBlock', (), {'label': 'événement', 'required': True}), 2: ('wagtail.blocks.RichTextBlock', (), {'label': 'Description', 'required': True}), 3: ('wagtail.blocks.StructBlock', [[('year', 0), ('event', 1), ('description', 2)]], {}), 4: ('wagtail.blocks.ListBlock', (3,), {})})),
                ('key_numbers', wagtail.fields.StreamField([('numbers', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'chiffre', 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'label', 'required': True}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'symbole', 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('number', 0), ('label', 1), ('symbol', 2)]], {}), 4: ('wagtail.blocks.ListBlock', (3,), {})})),
                ('leadership', wagtail.fields.StreamField([('members', 4)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'photo', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'nom', 'required': True}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'position', 'required': True}), 3: ('wagtail.blocks.StructBlock', [[('photo', 0), ('name', 1), ('position', 2)]], {}), 4: ('wagtail.blocks.ListBlock', (3,), {})})),
                ('hero_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name="Image d'en-tête")),
            ],
            options={
                'verbose_name': 'Page Qui sommes nous ?',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='RsePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('summary', models.TextField(blank=True, max_length=500, verbose_name="Résumé( sera affiché dans la page 'Qui sommes-nous ?' dans la section RSE)")),
                ('description', wagtail.fields.RichTextField(blank=True, verbose_name='Contenu de RSE')),
                ('award_section', wagtail.fields.RichTextField(blank=True, verbose_name='Contenu médaille')),
                ('images', wagtail.fields.StreamField([('image', 0)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'image médaille', 'required': True})})),
                ('values', wagtail.fields.StreamField([('values_items', 3)], blank=True, block_lookup={0: ('wagtail.blocks.TextBlock', (), {'label': 'titre', 'required': True}), 1: ('wagtail.blocks.RichTextBlock', (), {'label': 'Description', 'required': True}), 2: ('wagtail.blocks.StructBlock', [[('title', 0), ('description', 1)]], {}), 3: ('wagtail.blocks.ListBlock', (2,), {})})),
                ('key_numbers', wagtail.fields.StreamField([('numbers', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'chiffre', 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'label', 'required': True}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'symbole', 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('number', 0), ('label', 1), ('symbol', 2)]], {}), 4: ('wagtail.blocks.ListBlock', (3,), {})})),
                ('hero_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name="Image d'en-tête")),
            ],
            options={
                'verbose_name': 'Page RSE',
            },
            bases=('wagtailcore.page',),
        ),
    ]
