# Generated by Django 5.2.9 on 2025-12-28 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
        ('wagtaildocs', '0014_alter_document_file_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='rsepage',
            name='date_document',
            field=models.DateField(blank=True, null=True, verbose_name='Dernière mise à jour'),
        ),
        migrations.AddField(
            model_name='rsepage',
            name='document_rse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document', verbose_name='Document RSE'),
        ),
    ]
