# Generated by Django 5.2.9 on 2026-05-31 10:46

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatwedopage',
            name='vision_content',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='Vision & Mission content'),
        ),
        migrations.AlterField(
            model_name='whatwedopage',
            name='vision_title',
            field=models.CharField(default='Vision & Mission', max_length=255, verbose_name='Vision & Mission title'),
        ),
    ]
