# Generated by Django 5.2.9 on 2026-05-31 12:54

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_alter_whatwedopage_vision_content_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutpage',
            options={'verbose_name': 'About us'},
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='key_numbers',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='leadership',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='timeline',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='values',
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='images',
            field=wagtail.fields.StreamField([('image', 0)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'image médaille', 'required': True})}),
        ),
    ]
