# Generated by Django 5.2.9 on 2026-05-31 13:22

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_alter_aboutpage_options_remove_aboutpage_key_numbers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='client_logo',
            field=wagtail.fields.StreamField([('image', 0)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'our client logos', 'required': True})}),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='images',
            field=wagtail.fields.StreamField([('image', 0)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'about us images', 'required': True})}),
        ),
    ]
