# Generated by Django 5.2.9 on 2026-05-31 14:40

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_aboutpage_client_logo_alter_aboutpage_images'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='mission_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='image of the content'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='mission_content',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='mission_title',
            field=models.CharField(default='More details', max_length=255, verbose_name='More details'),
        ),
    ]
