# Generated by Django 5.2.9 on 2026-05-31 14:45

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_aboutpage_mission_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='history',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='history'),
        ),
    ]
