# Generated by Django 5.2.9 on 2026-05-31 15:31

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0006_aboutpage_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutpage',
            name='vision_content',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='vision_title',
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='certified',
            field=wagtail.fields.StreamField([('items', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Label', 'required': True}), 1: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'label': 'Document', 'required': True}), 2: ('wagtail.blocks.StructBlock', [[('label', 0), ('document', 1)]], {}), 3: ('wagtail.blocks.ListBlock', (2,), {})}),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='mission_content',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='content (More details)'),
        ),
    ]
