# Generated by Django 5.2.9 on 2026-06-01 16:03

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0007_remove_aboutpage_vision_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='mission_content',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='content (Our Story)'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='mission_title',
            field=models.CharField(default='Our Story', max_length=255, verbose_name='Our Story'),
        ),
    ]
