# Generated by Django 5.2.9 on 2026-05-30 14:36

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('introduction', wagtail.fields.RichTextField(blank=True, verbose_name='Introduction')),
                ('clients_title', models.CharField(default='Nos Clients', max_length=255, verbose_name='Titre de la section clients')),
                ('images', wagtail.fields.StreamField([('image', 0)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Logos clients', 'required': True})})),
                ('hero_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name="Image d'en-tête")),
                ('reviews_banner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Image de la section reviews')),
            ],
            options={
                'verbose_name': 'Page Réalisations / Clients',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ClientOpinion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('client_name', models.CharField(max_length=255, verbose_name='client')),
                ('quote', wagtail.fields.RichTextField(blank=True, verbose_name='avis de client')),
                ('author', models.CharField(blank=True, verbose_name='Poste')),
                ('logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Logo')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_opinion', to='portfolio.portfolioindexpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PortfolioPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('client_name', models.CharField(blank=True, max_length=255, verbose_name='Nom du project')),
                ('project_date', models.DateField(blank=True, null=True, verbose_name='Date du projet')),
                ('summary', models.TextField(blank=True, max_length=500, verbose_name='Résumé')),
                ('challenge', wagtail.fields.RichTextField(blank=True, verbose_name='Défi / Problématique')),
                ('solution', wagtail.fields.RichTextField(blank=True, verbose_name='Solution apportée')),
                ('results', wagtail.fields.RichTextField(blank=True, verbose_name='Résultats')),
                ('technologies', models.CharField(blank=True, help_text='Séparées par des virgules', max_length=500, verbose_name='Technologies utilisées')),
                ('project_url', models.URLField(blank=True, verbose_name='URL du projet')),
                ('featured_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Image principale')),
            ],
            options={
                'verbose_name': "Page cas d'étude",
            },
            bases=('wagtailcore.page',),
        ),
    ]
